apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multiargocluster
  name: multiargocluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiargocluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiargocluster
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
