apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multiargostgcluster
  name: multiargostgcluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multiargostgcluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiargostgcluster
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
