apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multiargoprodcluster
  name: multiargoprodcluster
spec:
  replicas: 4
  selector:
    matchLabels:
      app: multiargoprodcluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiargoprodcluster
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
